### ISSUE TITLE
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by mayanktiwariiiitdmj** [Charleshhy/One-shot-Human-Parsing#6]
When I am running the project from the following command:

```
bash scripts/evaluate_atr_kwf1.sh
```

I am getting the following error:

```
Traceback (most recent call last):
  File "./exp/train.py", line 14, in <module>
    from torchvision import transforms
  File "/home/mayank/anaconda3/envs/iniy_oneshothumanparsing_041221/lib/python3.7/site-packages/torchvision/__init__.py", line 1, in <module>
    from torchvision import models
  File "/home/mayank/anaconda3/envs/iniy_oneshothumanparsing_041221/lib/python3.7/site-packages/torchvision/models/__init__.py", line 11, in <module>
    from . import detection
  File "/home/mayank/anaconda3/envs/iniy_oneshothumanparsing_041221/lib/python3.7/site-packages/torchvision/models/detection/__init__.py", line 1, in <module>
    from .faster_rcnn import *
  File "/home/mayank/anaconda3/envs/iniy_oneshothumanparsing_041221/lib/python3.7/site-packages/torchvision/models/detection/faster_rcnn.py", line 7, in <module>
    from torchvision.ops import misc as misc_nn_ops
  File "/home/mayank/anaconda3/envs/iniy_oneshothumanparsing_041221/lib/python3.7/site-packages/torchvision/ops/__init__.py", line 1, in <module>
    from .boxes import nms, box_iou
  File "/home/mayank/anaconda3/envs/iniy_oneshothumanparsing_041221/lib/python3.7/site-packages/torchvision/ops/boxes.py", line 2, in <module>
    from torchvision import _C
ImportError: libcudart.so.9.0: cannot open shared object file: No such file or directory

```

This is the structure of the project:

```
.
├── data
│   ├── datasets
│   │   ├── ATR_OS
│   │   │   ├── list
│   │   │   │   ├── meta_test_id.txt
│   │   │   │   └── meta_train_id.txt
│   │   │   └── support
│   │   │       ├── meta_test_atr_supports.pkl
│   │   │       └── meta_train_atr_supports.pkl
│   │   ├── CIHP_OS
│   │   │   └── list
│   │   │       ├── meta_test_id.txt
│   │   │       └── meta_train_id.txt
│   │   └── LIP_OS
│   │       └── list
│   │           ├── meta_test_id.txt
│   │           └── meta_train_id.txt
│   └── pretrained_model
│       └── deeplab_v3plus_v3.pth
├── dataloaders
│   ├── mypath_atr.py
│   ├── mypath_mhp.py
│   ├── mypath.py
│   ├── oshp_loader.py
│   └── transforms.py
├── exp
│   ├── __init__.py
│   └── train.py
├── how_to_install.txt
├── imgs
│   ├── Figure1.jpg
│   └── Figure1.pdf
├── LICENSE
├── networks
│   ├── deeplab_xception_synBN.py
│   ├── eopnet.py
│   ├── __init__.py
│   └── popnet.py
├── README.md
├── requirements.txt
├── scripts
│   ├── atr_eop_1wf1.sh
│   ├── atr_eop_1wf2.sh
│   ├── atr_eop_kwf1.sh
│   ├── atr_eop_kwf2.sh
│   ├── cihp_eop_kwf1.sh
│   ├── cihp_eop_kwf2.sh
│   ├── evaluate_atr_1wf1.sh
│   ├── evaluate_atr_kwf1.sh
│   ├── lip_etop_kw_f1.sh
│   └── lip_etop_kw_f2.sh
├── sync_batchnorm
│   ├── batchnorm.py
│   ├── comm.py
│   ├── __init__.py
│   ├── replicate.py
│   └── unittest.py
└── utils
    ├── __init__.py
    ├── metric.py
    ├── sampler.py
    ├── test_human.py
    └── util.py
```

Please help me.

**Comment by Charleshhy** [comment]
Hi Dr. Mayank Tiwari,

Thanks for your interest in our project. It seems your CUDA version is not compatible with your `pytorch/torchvision `version. `ImportError: libcudart.so.9.0: cannot open shared object file: No such file or director` indicates that you have compiled `pytorch` with CUDA 9.0 while your current environment is not using the same CUDA version.

You may want to download the `pytorch` and `torchvision` from [here](https://pytorch.org/get-started/previous-versions/) that are compatible with your current CUDA version. Hope you can solve this problem soon!

Kind regards,
Haoyu
